// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIgnorePattern(arg1) {
  return window['go']['main']['App']['AddIgnorePattern'](arg1);
}

export function AddScanPath(arg1) {
  return window['go']['main']['App']['AddScanPath'](arg1);
}

export function CancelClean() {
  return window['go']['main']['App']['CancelClean']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RemoveIgnorePattern(arg1) {
  return window['go']['main']['App']['RemoveIgnorePattern'](arg1);
}

export function RemoveScanPath(arg1) {
  return window['go']['main']['App']['RemoveScanPath'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartClean(arg1) {
  return window['go']['main']['App']['StartClean'](arg1);
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateScanRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateScanRule'](arg1, arg2);
}
