// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddIgnorePattern(arg1:string):Promise<void>;

export function AddScanPath(arg1:string):Promise<void>;

export function CancelClean():Promise<void>;

export function CancelScan():Promise<void>;

export function GetConfig():Promise<models.Config>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveIgnorePattern(arg1:string):Promise<void>;

export function RemoveScanPath(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartClean(arg1:Array<models.ScanItem>):Promise<void>;

export function StartScan():Promise<models.ScanResult>;

export function UpdateConfig(arg1:models.Config):Promise<void>;

export function UpdateScanRule(arg1:string,arg2:boolean):Promise<void>;
